version: '3.8'

services:
  app:
    container_name: app-dev
    image: app-dev
    build: 
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - 4000:4000
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=project
      - DB_PORT=5432
    stdin_open: true
    tty: true